#!/usr/bin/perl
# sympa-sendmail: a sendmail(1) replacement for Sympa that submits each
# outbound message over SMTP to the MTA's DKIM2 signing listener on
# localhost (port DKIM2_SIGN_PORT, default 10587) instead of the local
# sendmail command, so list mail is signed by the outbound milter only.
# Point sympa.conf's "sendmail" at this script; set nrcpt 1 so each copy's
# rt= names one recipient. See docs/dkim2-postfix-list-host-guide.md.
use strict;
use warnings;
use IO::Socket::INET;

my $port = $ENV{DKIM2_SIGN_PORT} // 10587;
my $sender;
my @recips;
my $i = 0;
while ($i < @ARGV) {
    if ($ARGV[$i] eq "-f") {
        $sender = $ARGV[++$i];
    } elsif ($ARGV[$i] =~ /^-/) {
        # skip other flags (and their args if needed)
        $i++ if $ARGV[$i] =~ /^-[NVo]$/;
    } else {
        push @recips, $ARGV[$i];
    }
    $i++;
}
$sender //= "";

my $msg = do { local $/; <STDIN> };

my $sock = IO::Socket::INET->new(
    PeerAddr => "127.0.0.1",
    PeerPort => $port,
    Proto    => "tcp",
    Timeout  => 30,
) or die "Cannot connect to localhost:$port: $!\n";

sub smtp_read {
    my $line = <$sock>;
    die "SMTP error: $line" unless $line =~ /^[23]/;
    return $line;
}

smtp_read();
print $sock "EHLO localhost\r\n";
# Read all EHLO response lines
while (my $line = <$sock>) {
    last if $line =~ /^250 /;
    die "EHLO error: $line" unless $line =~ /^250-/;
}
print $sock "MAIL FROM:<$sender>\r\n"; smtp_read();
for my $r (@recips) {
    print $sock "RCPT TO:<$r>\r\n"; smtp_read();
}
print $sock "DATA\r\n"; smtp_read();
$msg =~ s/\r?\n/\r\n/g;
$msg =~ s/^\./\.\./gm;
print $sock $msg;
print $sock "\r\n.\r\n"; smtp_read();
print $sock "QUIT\r\n";
close $sock;
