server {
    listen 80;
    server_name sympa.dkim2.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sympa.dkim2.com;

    ssl_certificate /etc/letsencrypt/live/sympa.dkim2.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sympa.dkim2.com/privkey.pem;

    # Per-robot CSS is generated by Sympa into css_path (/var/lib/sympa/css);
    # served under the same /static-sympa/css/ URL the pages reference.
    location /static-sympa/css/ {
        alias /var/lib/sympa/css/;
    }

    # Static assets for the running Sympa 6.2.76 (dkim2 fork) live in its www/.
    location /static-sympa/ {
        alias /opt/sympa-dkim2/www/;
    }

    location /sympa {
        include fastcgi_params;
        fastcgi_pass unix:/run/sympa/wwsympa.socket;
    }

    location / {
        return 301 https://$host/sympa;
    }
}
