package Mail::DKIM2::DSNHeader;
use strict;
use warnings;

use MIME::Base64 qw(encode_base64 decode_base64);
use Crypt::Digest::SHA256 qw(sha256);

# NOTE: signing input uses dkim2_canonicalize_sig_header (all WSP removed),
# which is the function the rest of the codebase uses for *signature input*
# canonicalization (see Common::build_signing_input, spec Section 8.5).
# dkim2_canonicalize_header (WSP collapsed to a single space) is the
# *header hash* canonicalization (spec Section 5.2) and is not used here.
# As long as sign and verify below call the same function with the same
# blanked-signature string, the two stay identical -- that is the only
# correctness requirement for this header.
use Mail::DKIM2::Common qw(dkim2_canonicalize_sig_header fold_header to_rfc5321_path);

# Build the header value with the s= signature blanked (signing input form).
sub _value_blank_sig {
    my ($d, $rt_b64, $hh, $sel, $alg) = @_;
    return "d=$d; rt=$rt_b64; h=sha256:$hh; s=$sel:$alg:";
}

sub new {
    my ($class, %a) = @_;
    my $self = bless { d => $a{Domain}, hh => $a{HeaderHash},
                       sel => $a{Selector}, alg => $a{Algorithm} || 'rsa-sha256' }, $class;
    $self->{rt_b64} = encode_base64(to_rfc5321_path($a{RcptTo}), '');
    # signing input: canonicalized "DKIM2-DSN: <value with blank sig>"
    my $blank = "DKIM2-DSN: " . _value_blank_sig($self->{d}, $self->{rt_b64}, $self->{hh}, $self->{sel}, $self->{alg});
    my $input = dkim2_canonicalize_sig_header($blank);
    my $key = $a{Key};
    my $sig = ($self->{alg} =~ /^ed25519/)
        ? $key->sign_message(sha256($input))
        : $key->sign_message($input, 'SHA256', 'v1.5');
    $self->{sig_b64} = encode_base64($sig, '');
    return $self;
}

sub as_string {
    my ($self) = @_;
    my $val = "d=$self->{d}; rt=$self->{rt_b64}; h=sha256:$self->{hh}; "
            . "s=$self->{sel}:$self->{alg}:$self->{sig_b64}";
    return fold_header("DKIM2-DSN: $val");
}

sub parse {
    my ($class, $value) = @_;
    my $self = bless {}, $class;
    my %t; for my $p (split /\s*;\s*/, $value) { $p =~ /^(\w+)\s*=\s*(.*)/s or next;
        my ($k,$v)=($1,$2); $v =~ s/\s//gs; $t{$k}=$v; }
    $self->{d}   = $t{d};
    $self->{rt_b64} = $t{rt};
    ($self->{hh_full} = $t{h} // '') ;                 # "sha256:<hh>"
    ($self->{sel},$self->{alg},$self->{sig_b64}) = split /:/, ($t{s} // ''), 3;
    return $self;
}

sub domain      { $_[0]->{d} }
sub rcpt_to     { decode_base64($_[0]->{rt_b64} // '') }
sub header_hash { $_[0]->{hh_full} }                    # "sha256:<hh>"
sub selector    { $_[0]->{sel} }
sub algorithm   { $_[0]->{alg} }
sub signature   { decode_base64($_[0]->{sig_b64} // '') }

sub verify {
    my ($self, $pubkey) = @_;
    my ($hh) = ($self->{hh_full} // '') =~ /^sha256:(.*)$/ or return 0;
    my $blank = "DKIM2-DSN: " . _value_blank_sig($self->{d}, $self->{rt_b64}, $hh, $self->{sel}, $self->{alg});
    my $input = dkim2_canonicalize_sig_header($blank);
    my $sig = $self->signature;
    return $self->{alg} =~ /^ed25519/
        ? $pubkey->verify_message($sig, sha256($input))
        : $pubkey->verify_message($sig, $input, 'SHA256', 'v1.5');
}

1;

__END__

=head1 NAME

Mail::DKIM2::DSNHeader - Build/sign/parse/verify the DKIM2-DSN singleton header

=head1 SYNOPSIS

    use Mail::DKIM2::DSNHeader;

    my $h = Mail::DKIM2::DSNHeader->new(
        Domain     => 'example.com',
        RcptTo     => 'bounce@sender.example',
        HeaderHash => $header_hash_b64,   # bare base64, no "sha256:" prefix
        Selector   => 'sel1',
        Key        => $private_key,       # Crypt::PK::RSA or ::Ed25519
        Algorithm  => 'rsa-sha256',
    );
    print $h->as_string, "\n";            # "DKIM2-DSN: d=...; rt=...; h=...; s=...\r\n\t..."

    my $p = Mail::DKIM2::DSNHeader->parse($header_value);
    $p->domain; $p->rcpt_to; $p->header_hash; $p->selector; $p->algorithm;
    $p->verify($pubkey) or die "bad DKIM2-DSN signature";

=head1 DESCRIPTION

B<EXPERIMENTAL> — prototype support for a standalone C<DKIM2-DSN> header,
used to carry a signed reference (recipient + header hash) into a delivery
status notification generated by an MTA (e.g. Postfix) that does not have
access to the original DKIM2 signing context.

Tags:

=over 4

=item C<d=> - signing domain

=item C<rt=> - base64-encoded RFC 5321 forward-path (bracketed address)

=item C<h=> - C<sha256:> prefix followed by the base64 header hash being referenced

=item C<s=> - C<selector:algorithm:signature> triple, base64 signature

=back

The signing/verification input is the canonicalized C<DKIM2-DSN:> header
line with the C<s=> tag's signature value blanked (selector and algorithm
still present, trailing colon, no value) — the same blank-signature
construction pattern used by C<Mail::DKIM2::Signature>. Canonicalization
uses C<Mail::DKIM2::Common::dkim2_canonicalize_sig_header>, the same
function used to build DKIM2-Signature signing input (spec Section 8.5:
all whitespace removed) — as opposed to
C<dkim2_canonicalize_header>, which is used for header-hash computation
(Section 5.2: whitespace collapsed, not removed). Sign and verify must
(and do) use the identical canonicalized blanked-signature string.

=head1 AUTHOR

Bron Gondwana E<lt>brong@fastmailteam.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2025 Fastmail Pty Ltd.  This is free software; you can
redistribute it and/or modify it under the same terms as Perl itself.

=cut
